### ISSUE TITLE
"Колбеки на одинаковое событие будут объединены в один метод"

### ISSUE THREAD

**Issue by chestozo** [yandex-ui/noscript-view-edefine#1]
> Колбеки на одинаковое событие будут объединены в один метод

https://github.com/doochik/noscript-view-edefine/compare/master...yandex-ui:master#diff-c19230ea2a6b3209b8a7262d51af3cbaR8
`wrapperEvents` - смущает, что wrapper ничего не возвращает, это может быть не гуд для обработчиков событий.

Раньше события обработчики просто затирались и оставался последний подмешанный, но return не затирался. https://github.com/doochik/noscript-view-edefine/compare/master...yandex-ui:master#diff-391c7456947e216c7e5c4aa6339aa093L12
Сейчас мы их объединяем, но return value вообще нет.

**Comment by Katochimoto** [comment]
Это плохая практика для событий возвращать что либо, к примеру `false`, когда хотим событие остановить.
И от этого надо избавляться, для этого есть явные методы `event.preventDefault()` и `event.stopPropagation()`.
Почему плохая - хотя бы потому что специфичная для jQuery.

**Comment by chestozo** [comment]
Тогда может проверять, что метод вернул что-то отличное от `undefined` и ругаться?

**Comment by Katochimoto** [comment]
Да, это хорошая тема, сделаю

**Comment by Katochimoto** [comment]
https://github.com/yandex-ui/noscript-view-edefine/commit/15ac7afed0c350af50df3453e6aee3d8e0fffe7d
