### ISSUE TITLE
Тесты

### ISSUE THREAD

**Issue by chestozo** [yandex-ui/noscript-view-edefine#2]
- [x] на то, что `this` в обработчике события это вид
- <del>наследование методов - последовательность вызова (как для событий)</del>
- [ ] тест на мёрж моделей - в результирующем viewInfo будут именно те обработчики, которые указаны в миксинах / предке (уточнение вот этого теста https://github.com/doochik/noscript-view-edefine/compare/master...yandex-ui:3d839cd6c9971d0b839fa6da09720a2155dd52ea#diff-8136511aaf4eb65ad18072c0fea47efcR157)
- [ ] поправить тест - он на методы, а не события https://github.com/doochik/noscript-view-edefine/compare/master...yandex-ui:3d839cd6c9971d0b839fa6da09720a2155dd52ea#diff-8136511aaf4eb65ad18072c0fea47efcR367
- <del>тест на то, что объединённые отнаследованные методы вызываются оба</del>

**Comment by Katochimoto** [comment]
> наследование методов - последовательность вызова (как для событий)

это нет, они перетираются
сделаю варнинг в дебаге при попытке переопределения

**Comment by Katochimoto** [comment]
> тест на то, что объединённые отнаследованные методы вызываются оба

это соотв тоже не будет

**Comment by Katochimoto** [comment]
Тут подумал.
Давайте считать миксины "расширениями" а наследование "уточнением"?
То есть миксины не должны переопределять методы дитя или других миксинов.
Но дитё может "уточнять" т.е. переопределять метод предка.

Почему?
Потому что очень не хочется однажды получить миксин с абстрактным методом, и рядом другой миксин, который этот абстрактный метод реализует. При этом потомок вообще оказывается не при делах.

**Comment by Katochimoto** [comment]
и будем делать не варнинг а исключение

**Comment by Katochimoto** [comment]
передумали..

**Comment by Katochimoto** [comment]
https://github.com/yandex-ui/noscript-view-edefine/commit/c105e4ad866529dd20b0b8f94f79dab153180973
https://github.com/yandex-ui/noscript-view-edefine/commit/a54fb70aef094778962076f981c3a16de7a13146
https://github.com/yandex-ui/noscript-view-edefine/commit/8d1feb08e848a8c3da464bb6ae68dfecf60f69a1#diff-8136511aaf4eb65ad18072c0fea47efcR145

**Comment by Katochimoto** [comment]
тут тоже кажется всё
пиши, если что пропустил
